import os
from pathlib import Path
from textwrap import dedent

PROJECT_ROOT = Path(__file__).parent


def main():
    # 1. Create folders
    package_dir = PROJECT_ROOT / "src" / "fastapi_boilerplate_agent"
    examples_dir = PROJECT_ROOT / "examples"

    for d in [package_dir, examples_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # 2. Root files
    files = {}

    files[PROJECT_ROOT / "README.md"] = dedent(
        """\
        # fastapi-boilerplate-agent

        An AI-powered agent (LangChain + LangGraph) that generates
        a FastAPI backend boilerplate from a natural language request.

        ## Features (MVP)

        - Parse user request into a structured project configuration
        - Generate a minimal FastAPI project structure
        - Support for Postgres/SQLite, Docker, and basic CI templates

        ## Quick start

        ```bash
        python -m venv .venv
        source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate
        pip install -e .
        python -m fastapi_boilerplate_agent.cli
        ```
        """
    )

    files[PROJECT_ROOT / ".gitignore"] = dedent(
        """\
        .venv/
        __pycache__/
        .pytest_cache/
        .DS_Store
        *.pyc
        """
    )

    # You can also use requirements.txt if you prefer
    files[PROJECT_ROOT / "pyproject.toml"] = dedent(
        """\
        [project]
        name = "fastapi-boilerplate-agent"
        version = "0.1.0"
        description = "LangGraph agent that generates a FastAPI backend boilerplate."
        authors = [
          { name = "Martial Wafo" }
        ]
        requires-python = ">=3.11"
        dependencies = [
          "fastapi",
          "langchain",
          "langchain-openai",
          "langgraph",
          "pydantic>=2",
        ]

        [project.optional-dependencies]
        dev = ["pytest"]

        [build-system]
        requires = ["setuptools", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        where = ["src"]
        """
    )

    # 3. Package files
    files[package_dir / "__init__.py"] = dedent(
        """\
        """
    )

    files[package_dir / "config.py"] = dedent(
        """\
        from typing import Literal
        from pydantic import BaseModel


        class ProjectConfig(BaseModel):
            \"\"\"Minimal configuration for a FastAPI project.

            This config is generated by the LLM from
            a natural language request.
            \"\"\"

            project_name: str
            db: Literal["postgres", "sqlite"] = "postgres"
            auth_enabled: bool = True
            docker: bool = True
            ci: Literal["gitlab", "github", "none"] = "gitlab"
        """
    )

    files[package_dir / "tools.py"] = dedent(
        """\
        from langchain.tools import tool
        from typing import Dict


        BASE_MAIN = \"\"\"\
        from fastapi import FastAPI

        app = FastAPI(title="{project_name}")


        @app.get("/health")
        def health():
            return {{"status": "ok"}}
        \"\"\"


        DB_CONFIG = {{
            "postgres": 'SQLALCHEMY_DATABASE_URI = "postgresql://user:pass@db:5432/app"',
            "sqlite": 'SQLALCHEMY_DATABASE_URI = "sqlite:///./app.db"',
        }}


        DOCKERFILE = \"\"\"\
        FROM python:3.11-slim

        WORKDIR /app
        COPY . /app

        RUN pip install -r requirements.txt

        CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        \"\"\"


        GITLAB_CI = \"\"\"\
        stages:
          - test
          - build

        test:
          stage: test
          script:
            - pip install -r requirements.txt
            - pytest
        \"\"\"


        GITHUB_ACTIONS = \"\"\"\
        name: CI

        on: [push]

        jobs:
          test:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: actions/setup-python@v5
                with:
                  python-version: "3.11"
              - run: pip install -r requirements.txt
              - run: pytest
        \"\"\"


        REQUIREMENTS = \"\"\"\
        fastapi
        uvicorn[standard]
        sqlalchemy
        pydantic
        pytest
        \"\"\"


        @tool
        def generate_fastapi_boilerplate(config: Dict) -> Dict[str, str]:
            \"\"\"Generate a minimal FastAPI boilerplate.

            Args:
                config: A dict following ProjectConfig fields.

            Returns:
                Mapping of file path -> file content.
            \"\"\"
            project_name = config.get("project_name", "fastapi_app")
            db = config.get("db", "postgres")
            ci = config.get("ci", "gitlab")
            docker = config.get("docker", True)

            files: Dict[str, str] = {{}}

            files["app/main.py"] = BASE_MAIN.format(project_name=project_name)
            files["app/config.py"] = DB_CONFIG[db] + "\\n"
            files["requirements.txt"] = REQUIREMENTS

            if docker:
                files["Dockerfile"] = DOCKERFILE

            if ci == "gitlab":
                files[".gitlab-ci.yml"] = GITLAB_CI
            elif ci == "github":
                files[".github/workflows/ci.yml"] = GITHUB_ACTIONS

            return files
        """
    )

    files[package_dir / "graph.py"] = dedent(
        """\
        from typing import Optional, Dict

        from typing_extensions import TypedDict
        from langchain_openai import ChatOpenAI
        from langchain_core.prompts import ChatPromptTemplate
        from langchain_core.output_parsers import PydanticOutputParser
        from langchain_core.runnables import RunnableLambda
        from langgraph.graph import StateGraph, END

        from .config import ProjectConfig
        from .tools import generate_fastapi_boilerplate


        class State(TypedDict):
            user_request: str
            config: Optional[dict]
            files: Optional[Dict[str, str]]


        llm = ChatOpenAI(model="gpt-4o-mini")

        parser = PydanticOutputParser(pydantic_object=ProjectConfig)

        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You convert a user request into a ProjectConfig configuration. "
                    "Respond only with valid JSON.",
                ),
                ("human", "{user_request}"),
            ]
        )


        def to_config_dict(user_request: str) -> dict:
            msg = prompt.format_messages(user_request=user_request)
            result = llm.invoke(msg)
            config = parser.parse(result.content)
            return config.dict()


        def build_config(state: State) -> State:
            config = to_config_dict(state["user_request"])
            return {{**state, "config": config}}


        def generate_code(state: State) -> State:
            files = generate_fastapi_boilerplate.invoke(state["config"])
            return {{**state, "files": files}}


        def build_app():
            graph = StateGraph(State)
            graph.add_node("build_config", build_config)
            graph.add_node("generate_code", generate_code)

            graph.set_entry_point("build_config")
            graph.add_edge("build_config", "generate_code")
            graph.add_edge("generate_code", END)

            return graph.compile()
        """
    )

    files[package_dir / "cli.py"] = dedent(
        """\
        from pathlib import Path
        from .graph import build_app


        def main():
            user_request = (
                "Generate a FastAPI backend called 'crm_backend' with Postgres, "
                "auth, Docker and GitLab CI."
            )

            app = build_app()
            state = {{ "user_request": user_request, "config": None, "files": None }}
            result = app.invoke(state)

            files = result.get("files") or {{}}
            out_dir = Path("generated_project")
            out_dir.mkdir(exist_ok=True)

            for path, content in files.items():
                file_path = out_dir / path
                file_path.parent.mkdir(parents=True, exist_ok=True)
                file_path.write_text(content, encoding="utf-8")

            print(f"Generated project in: {out_dir.resolve()}")


        if __name__ == "__main__":
            main()
        """
    )

    # Example
    files[examples_dir / "sample_request.txt"] = (
        "Generate a FastAPI backend for a CRM with Postgres, Docker, "
        "authentication and GitLab CI.\n"
    )

    # 4. Write all files
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")

    print(f"Project created in: {PROJECT_ROOT.resolve()}")


if __name__ == "__main__":
    main()
